# Generated by Django 6.0.7 on 2026-07-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=190)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
                ('conected', models.BooleanField(default=False)),
                ('session', models.CharField(max_length=100)),
                ('session_started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
