# Generated by Django 6.0.7 on 2026-07-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conected',
            new_name='connected',
        ),
    ]
