# Generated by Django 6.0.7 on 2026-07-20 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_conected_user_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('token', models.CharField(max_length=255)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='users.user',
                    ),
                ),
            ],
            options={
                'db_table': 'refresh_token',
            },
        ),
    ]
