# Generated by Django 6.0.7 on 2026-07-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
