# Generated by Django 6.0.7 on 2026-07-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_access_contacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lid',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
