# Generated by Django 6.0.7 on 2026-07-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_contact_lid_alter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
