# Generated by Django 6.0.7 on 2026-07-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contact_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lid',
        ),
    ]
