# Generated by Django 6.0.7 on 2026-07-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_contact_lid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
