# Generated by Django 6.0.7 on 2026-07-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('message', models.CharField(max_length=290)),
                ('time', models.TimeField()),
                ('number', models.CharField(max_length=60)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('sent', 'SENT'),
                            ('pending', 'PENDING'),
                            ('process', 'PROCESS'),
                        ],
                        default='pending',
                        max_length=45,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
