# Generated by Django 6.0.7 on 2026-07-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
