# Generated by Django 6.0.7 on 2026-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
        migrations.AddField(
            model_name='message',
            name='scheduled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
